version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fisa
      - DB_PORT=5432
    ports:
      - 5432:5432
  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - 6379:6379
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis